WIDTH = 1280
HEIGHT = 720
GROUND_OFFSET = 50
GROUND_Y = HEIGHT - GROUND_OFFSET
ASSETS_PATH = "Assets/"
MUSIC_PATH = "Media/Music/"
SFX_PATH = "Assets/SFX/"
SFX_VOLUME = 0.7 # volumen efectos (0.0 - 1.0)
CLOCK_FPS = 60
SPEED = 5
GRAVITY = 0.5
AXIS_DEADZONE = 0.5
SHOW_HITBOX = True
MAX_IMPURITY = 140
MAX_LVL = 100

# Salud y plegarias de Lilie 
MAX_HEALING_PRAYERS = 3         
PRAYER_HEAL_RATIO = 0.45         
PRAYER_CANCELLED_BY_DAMAGE = True
HURT_INVULN_MS = 700
HURT_FLASH_MS = 250
DASH_INVULN_GRACE_MS = 80
DASH_ALPHA = 170
HUD_MARGIN = 24

# Cinemáticas
VIDEO_PATH = "Assets/Videos/"
VIDEO_SKIP_MS = 1200
VIDEO_FUNDIDO_MS = 5000